site:
  title: Rodnan Sol
  url: https://rodnansol.github.io/
  start_page: ROOT::index.adoc
  robots: allow
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs
    - url: https://github.com/rodnansol/spring-configuration-property-documenter
      start_path: docs
      branches: master
    - url: https://github.com/rodnansol/jbang-catalog-document-generator
      start_path: docs
      branches: master
    - url: https://github.com/rodnansol/commit-teller
      start_path: docs
      branches: master

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
    - path: partials/head-meta.hbs
      contents: ./supplemental-ui/partials/head-meta.hbs
    - path: partials/head-icons.hbs
      contents: ./supplemental-ui/partials/head-icons.hbs
    - path: partials/header-content.hbs
      contents: ./supplemental-ui/partials/header-content.hbs
    - path: partials/nav-explore.hbs
      contents: ./supplemental-ui/partials/nav-explore.hbs
    - path: img/favicon.ico
      contents: ./supplemental-ui/favicon.ico

antora:
  extensions:
    - '@antora/lunr-extension'
